### ISSUE TITLE
Does not work on GNOME 42, even when bypassing the version check

### ISSUE THREAD

**Issue by JordanViknar** [p-e-w/argos#135]
The error given is : Object 0x2a6733826970 is not a subclass of GObject_Object, it's a Object

![image](https://user-images.githubusercontent.com/74505993/162235769-a09c1704-196c-40cf-a7f3-3793029e48a8.png)

Argos does not function at all.

**Comment by Coda-Coda** [comment]
I also get a similar error, also bypasssing the version check.

**Comment by Coda-Coda** [comment]
Hi @JordanViknar,
I have now fixed this issue in a fork of this repository. It should work for GNOME 42 now. It works for my use-case, at least. Hope it helps. :slightly_smiling_face: 
Here's the repository: https://github.com/Coda-Coda/argos/tree/gnome-42
Here's the commit with the changes, if you're interested: https://github.com/Coda-Coda/argos/commit/ab53846fc92639b826da3e36818e5525701dcc9c

**Comment by JordanViknar** [comment]
Actually, I noticed I somehow missed a pull request that has the fixes for GNOME 42 already. 

Unless your solution is different/works better, sorry for wasting your time. 

I'm gonna keep this issue opened though, since this is still a problem in the main version of Argos.

**Comment by Coda-Coda** [comment]
@JordanViknar Good point, I didn't notice the pull request either actually. Their fixes are very similar to mine. Ah well, I learnt things about GNOME along the way :slightly_smiling_face: 
One minor difference is that I optimistically put all GNOME versions from 42-49 as supported, so _if nothing breaks_ the extension will just keep working without needing bump the supported version list until GNOME 50.

For others who see this issue, this is their pull request: https://github.com/p-e-w/argos/pull/134.

**Comment by prurigro** [comment]
@Coda-Coda The version in the PR doesn't populate my dropdown menu while yours does, so it might be worth making a PR with yours too just in case it works better for others too? Thanks BTW!

**Comment by Coda-Coda** [comment]
@prurigro thanks for noticing that. I've left a [comment on their pull request](https://github.com/p-e-w/argos/pull/134#issuecomment-1096143280) which hopefully will be resolved rather than making an additional pull request.

**Comment by mwilck** [comment]
> One minor difference is that I optimistically put all GNOME versions from 42-49 as supported, 

That's wrong. You can never be sure that future GNOME releases won't break your extension, past experience proves this very clearly.

Also, as I said in #134, @Coda-Coda's code needs to be rebased to current master. Once it is, and works better than mine, by all means let's go ahead with a PR.

@prurigro, please describe the issues you had with #134 there if you have time.

**Comment by Coda-Coda** [comment]
@mwilck thanks for your comment.

> That's wrong. You can never be sure that future GNOME releases won't break your extension, past experience proves this very clearly.

I'm well aware of this (which is why I said "optimistically"), however in the (unlikely) scenario that GNOME 43 (etc) doesn't break Argos then my approach will save me the hassle of having Argos break (solely due to not listing `"43"`) and needing to bump the version number which is a minor hassle (and if Argos does break, then I'll just figure out how to fix it). In saying that, I wouldn't create a pull request to this repo with the version numbers like that, because it's more like a workaround to save me some hassle than a principled approach.

> @prurigro, please describe the issues you had with https://github.com/p-e-w/argos/pull/134 there if you have time.

I agree, this would be helpful especially since you (@mwilck) mention that they work fine for you. But best to have this discussion over in https://github.com/p-e-w/argos/pull/134.

**Comment by mwilck** [comment]
> then my approach will save me the hassle of having Argos break (solely due to not listing "43")

Of course. It's fine for your private version, where you can do what you like, but not for an official PR.

**Comment by brad** [comment]
I tried a few different branches and the only one I found working with gnome shell 42 is https://github.com/Coda-Coda/argos/tree/gnome-42-for-mwilck
It's not an easy merge though

**Comment by 11qeq11** [comment]
@brad Thanks mate, that actually worked with version 42.9.

**Comment by mwilck** [comment]
As we have just a single branch (which was the project owner's preference), this is kind of hard to fix now, because GNOME 42 support has been dropped on the main branch.

@brad, @11qeq11, can you perhaps try checking out 59732ba and just changing `const ArgosMenuItem` to `var ArgosMenuItem` in `menuitem.js`?
